version: '2.1'

services:
  node-app:
    image: node-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js